// On-demand AI narrative for an IOC. Purely user-triggered (the "Explain"
// button); the generated text already carries the backend's verification
// disclaimer, and we surface the model that produced it.

import type { UseNarrative } from "../hooks/useNarrative";

interface NarrativePanelProps {
  ioc: string;
  narrative: UseNarrative;
}

export function NarrativePanel({ ioc, narrative }: NarrativePanelProps) {
  const { data, loading, error, explain } = narrative;

  return (
    <section className="detail__section">
      <div className="detail__section-head">
        <h3 className="detail__section-title">AI narrative</h3>
        <button
          className="detail__action"
          onClick={() => explain(ioc)}
          disabled={loading}
        >
          {loading ? "Generating…" : data ? "Regenerate" : "Explain"}
        </button>
      </div>

      {error && <p className="detail__error">{error}</p>}

      {data && (
        <>
          <p className="detail__narrative">{data.narrative}</p>
          <p className="detail__meta">Generated by {data.model}</p>
        </>
      )}

      {!data && !error && !loading && (
        <p className="detail__hint">
          Generate an on-demand, evidence-grounded explanation of this indicator's
          subgraph. Runs an LLM call, so it is triggered only on request.
        </p>
      )}
    </section>
  );
}
